name: linux-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 10
      matrix:
        python-version: ["3.8.x", "3.9.x", "3.10.x", "3.11.x", "3.12.x"]
        os: [ubuntu-latest, ubuntu-22.04]
    steps:
    - uses: actions/checkout@v4
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip pytest pytest-asyncio coverage aiofiles cryptography
    - name: test with pytest
      run: |
        coverage run --omit="aiootp/__engagement/*" --source aiootp -p -m pytest -vv tests/test_aiootp.py
        coverage combine
        coverage report
