name: windows-build

on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        python-version: ["3.8.x", "3.9.x", "3.10.x", "3.11.x", "3.12.x", "3.13.x"]
        os: [windows-latest]
    steps:
    - uses: actions/checkout@v4
    - name: setup python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: install dependencies
      run: |
        python3 -m pip install --upgrade pip pytest pytest-asyncio coverage ruff hypothesis aiofiles cryptography
    - name: lint with ruff
      run: |
        ruff check . && ruff format --line-length=76 --check .
    - name: test with pytest
      run: |
        coverage run --omit="aiootp/__engagement/*" --source aiootp -p -m pytest -vv tests/test_aiootp.py
        coverage combine
        coverage report
